[package]
name = "leetcode"
version = "0.1.0"
authors = ["zhyuri <zhang1437@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "leetcode"
doctest = false
test = true
